### ISSUE TITLE
Encountered `panic: runtime error: invalid memory address or nil pointer dereference`

### ISSUE THREAD

**Issue by civitaspo** [kayac/ecspresso#568]
Hi maintainers, I encountered the error `panic: runtime error: invalid memory address or nil pointer dereference`, so I report this. I think that temporarily AWS API returned an unexpected response as the issue was resolved when I reran it. There is no immediate urgency.

version: v2.1.0
command: `ecspresso run --config=ecspresso.jsonnet --task-def=sample-taskdef.json --watch-container=sample-container`

The detailed error message is below.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1505ce4]

goroutine 1 [running]:
github.com/kayac/ecspresso/v2.(*App).RunTask(0xc00016b500, {0x1b1ad70, 0xc000334510}, {0xc0007c9a40, 0x63}, 0xc00084ac00, 0xc000a7fbb0)
	/home/runner/work/ecspresso/ecspresso/run.go:158 +0x8a4
github.com/kayac/ecspresso/v2.(*App).Run(0x0?, {0x1b1b710?, 0xc00011cd80?}, {0xc0000eb9f9, 0xc000[26](https://github.com/LayerXcom/layerone/actions/runs/5051078393/jobs/9062570888#step:7:27)fd30, 0xc0000eba09, 0xc000316b80, 0xc000316bb0, 0xc0000eba21, 0xc0000eba28, ...})
	/home/runner/work/ecspresso/ecspresso/run.go:80 +0x771
github.com/kayac/ecspresso/v2.dispatchCLI({0x1b1b710, 0xc00011cd80}, {0xc00031ba96, 0x3}, 0xc000317030, 0xc0004660f0)
	/home/runner/work/ecspresso/ecspresso/cli.go:111 +0x[27](https://github.com/LayerXcom/layerone/actions/runs/5051078393/jobs/9062570888#step:7:28)c
github.com/kayac/ecspresso/v2.CLI({0x1b1b710, 0xc00011cd80}, 0x24fad60?)
	/home/runner/work/ecspresso/ecspresso/cli.go:147 +0x99
main.main()
	/home/runner/work/ecspresso/ecspresso/cmd/ecspresso/main.go:19 +0x9b
run a command: exit status 2
```

**Comment by fujiwara** [comment]
@civitaspo Thank you for reporting!

I've fixed this by #569. I couldn't reproduce it, but the code became more robust.
